### ISSUE TITLE
Missing hits

### ISSUE THREAD

**Issue by SafiaSafa** [cran/BHTSpack#1]
Hello,

 I am currently using BHTSpack to highlight candidate hits from a highthrouput single dose screen. First, I normalized my data (computing a Cscore, an analogue of inhibition calculation that can be interpreted the same way), I think that a compound with a high Cscore (more than 70%) have a high probability to be a hit.
But when I use BHTSpack I observe some compound with higher Csore values not being labeled as hits. 
![Sample2_anon](https://user-images.githubusercontent.com/26387418/142915822-dd6f872b-8f04-4769-99bc-916aadaa778b.png)
This is the file I use to generate those data : [Uploading Sample2_anon.txt…]()
This is my code : 
```
library(BHTSpack)
library(tidyverse)
library(ggplot2)
set.seed(1234)


ele = 'Sample2_anon.txt'
output_file <- tools::file_path_sans_ext(ele)

X16H110 <- read.csv(ele, sep="\t")
test <- X16H110[c('Plate','Cscore')]
Z <- lapply(split(test[-1], test$Plate), function(x) x[x != ""])
for (i in 1:length(names(Z))){
    p = names(Z)[i]
    names(Z[[p]])<- as.list(X16H110[X16H110$Plate == names(Z)[1],"Well"])
}
            
v = var(test$Cscore)
mu= mean(test$Cscore)

a=((v^2)/10^-4)+2
b=((v^3)/10^-4)+v

system.time(b.est <- bhts(Z, iters=7000, H=10, K=10, mu00=0.5*mu, mu10=3*mu, a.alpha=a, b.alpha=b, a.tau=a, b.tau=b, s=1234, store=TRUE))
            
res = r.fdr(b.est, fdr=0.05)
res[["r"]]
# Significant compound hit list
sign =  res[["res"]]
            
            
proba_all = data.frame(unlist(b.est$hatpai))
proba_all[,2]=row.names(proba_all)
row.names(proba_all)<-NULL
colnames(proba_all)<-c("hatpai","ID")
proba_all = proba_all %>%
  separate(ID, c("Plate", "Well"), "\\.")

out = merge(X16H110, proba_all)


ggplot(out, aes(x=Cscore, y=hatpai)) + 
    geom_point() + 
    geom_hline(aes(yintercept=res[["r"]], linetype = paste('Cutoff:', (res[["r"]]))), show.legend = TRUE)+ 
    ggtitle(unique(out$Sample))+
    theme(plot.title = element_text(hjust = 0.5))+
    theme(legend.title=element_blank())
ggsave(file=paste(output_file, ".png")) 

```
I observe this phenomenon on different samples. The compound for each sample are not placed on the same plate or show any pattern. The plates don't contain any plate effect. And they are different for each sample. I don't know why this happened do you have any idea, please?

![BHTSpack_issue](https://user-images.githubusercontent.com/26387418/142915694-09412415-142a-4052-a835-64129060a083.PNG)

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by SafiaSafa** [comment]
Ok thank you I am contacting him.
